import { useMemo } from "react";
import type { EditorView } from "./EditorView";
import type {
  EditorHeaderModel,
  EditorSidebarModel,
  EditorTimelineModel,
  MixerPanelModel,
  PlayerControlsModel,
} from "./componentModels";

export function useEditorComponentModels(view: EditorView) {
  const editorHeaderModel = useMemo<EditorHeaderModel>(
    () => ({
      headerRenderKey: view.headerRenderKey,
      projectName: view.projectName,
      savedLabel: view.savedLabel,
      zoomLabel: view.zoomLabel,
      aspectLabel: view.aspectLabel,
      onOpenExport: view.onOpenExport,
      exportLabel: view.exportLabel,
      minimizeWindowLabel: view.minimizeWindowLabel,
      onMinimizeWindow: view.onMinimizeWindow,
      maximizeWindowLabel: view.maximizeWindowLabel,
      onToggleMaximizeWindow: view.onToggleMaximizeWindow,
      closeWindowLabel: view.closeWindowLabel,
      onCloseWindow: view.onCloseWindow,
    }),
    [view.headerRenderKey]
  );
  const playerControlsModel = useMemo<PlayerControlsModel>(
    () => ({
      formattedCurrentTime: view.formattedCurrentTime,
      duration: view.duration,
      currentTime: view.currentTime,
      onSeekInput: view.onSeekInput,
      onSkipBack: view.onSkipBack,
      isAudioReady: view.isAudioReady,
      onTogglePlayback: view.onTogglePlayback,
      isPlaying: view.isPlaying,
      onSkipForward: view.onSkipForward,
    }),
    [view.currentTime, view.isAudioReady, view.isPlaying]
  );
  const mixerPanelModel = useMemo<MixerPanelModel>(
    () => ({
      mixerLabel: view.mixerLabel,
      instrumentalVolumeLabel: view.instrumentalVolumeLabel,
      instrumentalVolume: view.instrumentalVolume,
      onInstrumentalVolumeChange: view.onInstrumentalVolumeChange,
      vocalsVolumeLabel: view.vocalsVolumeLabel,
      vocalsVolume: view.vocalsVolume,
      onVocalsVolumeChange: view.onVocalsVolumeChange,
    }),
    [view.sidebarRenderKey]
  );
  const editorTimelineModel = useMemo<EditorTimelineModel>(
    () => ({
      timelineRenderKey: view.timelineRenderKey,
      tracksLabel: view.tracksLabel,
      addSubtitleTrackLabel: view.addSubtitleTrackLabel,
      onAddSubtitleTrack: view.onAddSubtitleTrack,
      timelineToolsLabel: view.timelineToolsLabel,
      splitToolActive: view.splitToolActive,
      pointerToolLabel: view.pointerToolLabel,
      onSelectPointerTool: view.onSelectPointerTool,
      splitToolLabel: view.splitToolLabel,
      onToggleSplitTool: view.onToggleSplitTool,
      markerToolActive: view.markerToolActive,
      markerToolLabel: view.markerToolLabel,
      onToggleMarkerTool: view.onToggleMarkerTool,
      joinPhrasesDisabled: view.joinPhrasesDisabled,
      joinPhrasesLabel: view.joinPhrasesLabel,
      onJoinPhrases: view.onJoinPhrases,
      timelineSubdivision: view.timelineSubdivision,
      timelineSnapToGrid: view.timelineSnapToGrid,
      subdivisionLabel: view.subdivisionLabel,
      snapToGridLabel: view.snapToGridLabel,
      onSubdivisionChange: view.onSubdivisionChange,
      onSnapToGridChange: view.onSnapToGridChange,
      timelineAutoFollow: view.timelineAutoFollow,
      onTimelineAutoFollowChange: view.onTimelineAutoFollowChange,
      timelineAutoFollowLabel: view.timelineAutoFollowLabel,
      bpmLabel: view.bpmLabel,
      bpmInputValue: view.bpmInputValue,
      onBpmInput: view.onBpmInput,
      onBpmBlur: view.onBpmBlur,
      onBpmKeyDown: view.onBpmKeyDown,
      beatOffsetLabel: view.beatOffsetLabel,
      maximumTempoOffsetSeconds: view.maximumTempoOffsetSeconds,
      tempoOffsetSeconds: view.tempoOffsetSeconds,
      onBeatOffsetInput: view.onBeatOffsetInput,
      formattedDuration: view.formattedDuration,
      timelineLabelsRef: view.timelineLabelsRef,
      timelineRows: view.timelineRows,
      getTimelineRowId: view.getTimelineRowId,
      selectedTrackId: view.selectedTrackId,
      timelineRef: view.timelineRef,
      onTimelineScroll: view.onTimelineScroll,
      timelineContentRef: view.timelineContentRef,
      timelineContentStyle: view.timelineContentStyle,
      onTimelineClick: view.onTimelineClick,
      hideTimelineGrid: view.hideTimelineGrid,
      timelineGridLines: view.timelineGridLines,
      hideTimelineClips: view.hideTimelineClips,
      renderTimelineRow: view.renderTimelineRow,
      hideTimelinePlayhead: view.hideTimelinePlayhead,
      timelinePlayheadRef: view.timelinePlayheadRef,
      timelineMarkers: view.timelineMarkers,
      duration: view.duration,
      timelineMarkerDeleteLabel: view.timelineMarkerDeleteLabel,
      onRemoveTimelineMarker: view.onRemoveTimelineMarker,
      onRemoveAllTimelineMarkers: view.onRemoveAllTimelineMarkers,
      removeAllTimelineMarkersLabel: view.removeAllTimelineMarkersLabel,
      removeAllTimelineMarkersDisabled: view.removeAllTimelineMarkersDisabled,
      onSelectTrack: view.onSelectTrack,
      onRenameTrack: view.onRenameTrack,
    }),
    [view.timelineRenderKey]
  );
  const editorSidebarModel = useMemo<EditorSidebarModel>(
    () => ({
      onColorPreviewEnd: view.onColorPreviewEnd,
      trackPositionX: view.trackPositionX,
      trackPositionY: view.trackPositionY,
      positionXLabel: view.positionXLabel,
      positionYLabel: view.positionYLabel,
      scaleLabel: view.scaleLabel,
      readAnimationLabel: view.readAnimationLabel,
      getCurveOptionId: view.getCurveOptionId,
      renderCurveOption: view.renderCurveOption,
      fontFamilyLabel: view.fontFamilyLabel,
      fontOptions: view.fontOptions,
      getFontOptionId: view.getFontOptionId,
      fontStyleLabel: view.fontStyleLabel,
      boldLabel: view.boldLabel,
      italicLabel: view.italicLabel,
      underlineLabel: view.underlineLabel,
      superscriptLabel: view.superscriptLabel,
      subscriptLabel: view.subscriptLabel,
      inheritLabel: view.inheritLabel,
      unreadLabel: view.unreadLabel,
      readLabel: view.readLabel,
      bezierLabels: view.bezierLabels,
      sidebarRenderKey: view.sidebarRenderKey,
      backgroundTrackSelected: view.backgroundTrackSelected,
      backgroundClipLabel: view.backgroundClipLabel,
      backgroundPresetLabel: view.backgroundPresetLabel,
      backgroundPreset: view.backgroundPreset,
      onBackgroundPresetChange: view.onBackgroundPresetChange,
      backgroundAlbumArtLabel: view.backgroundAlbumArtLabel,
      backgroundVideoLabel: view.backgroundVideoLabel,
      backgroundImageLabel: view.backgroundImageLabel,
      backgroundSolidLabel: view.backgroundSolidLabel,
      backgroundGradientLabel: view.backgroundGradientLabel,
      backgroundAsset: view.backgroundAsset,
      backgroundReplaceLabel: view.backgroundReplaceLabel,
      backgroundChooseLabel: view.backgroundChooseLabel,
      onBackgroundAssetImport: view.onBackgroundAssetImport,
      backgroundAssetName: view.backgroundAssetName,
      backgroundSelectedFileLabel: view.backgroundSelectedFileLabel,
      backgroundFitLabel: view.backgroundFitLabel,
      backgroundFit: view.backgroundFit,
      onBackgroundChange: view.onBackgroundChange,
      backgroundColorLabel: view.backgroundColorLabel,
      backgroundColor: view.backgroundColor,
      backgroundGradientStartLabel: view.backgroundGradientStartLabel,
      backgroundGradientStart: view.backgroundGradientStart,
      backgroundGradientEndLabel: view.backgroundGradientEndLabel,
      backgroundGradientEnd: view.backgroundGradientEnd,
      backgroundGradientAngleLabel: view.backgroundGradientAngleLabel,
      backgroundGradientAngle: view.backgroundGradientAngle,
      selectedSubtitleTrack: view.selectedSubtitleTrack,
      trackStyleLabel: view.trackStyleLabel,
      trackTabActive: view.trackTabActive,
      onShowTrackTab: view.onShowTrackTab,
      phraseTabActive: view.phraseTabActive,
      onShowPhraseTab: view.onShowPhraseTab,
      phraseStyleLabel: view.phraseStyleLabel,
      wordTabActive: view.wordTabActive,
      onShowWordTab: view.onShowWordTab,
      wordStyleLabel: view.wordStyleLabel,
      animationTemplateLabel: view.animationTemplateLabel,
      animationTemplate: view.animationTemplate,
      onAnimationTemplateChange: view.onAnimationTemplateChange,
      animationTemplateOneLabel: view.animationTemplateOneLabel,
      animationTemplateOneDescription: view.animationTemplateOneDescription,
      onRequestDeleteTrack: view.onRequestDeleteTrack,
      deleteTrackLabel: view.deleteTrackLabel,
      activePhrase: view.activePhrase,
      textLabel: view.textLabel,
      onPhraseTextCommit: view.onPhraseTextCommit,
      startLabel: view.startLabel,
      onPhraseStartInput: view.onPhraseStartInput,
      endLabel: view.endLabel,
      onPhraseEndInput: view.onPhraseEndInput,
      wordsLabel: view.wordsLabel,
      inspectorWords: view.inspectorWords,
      getWordId: view.getWordId,
      selectedWord: view.selectedWord,
      wordTextLabel: view.wordTextLabel,
      gapLabel: view.gapLabel,
      onInspectorWordSelect: view.onInspectorWordSelect,
      onInspectorWordTextInput: view.onInspectorWordTextInput,
      onInspectorWordStartInput: view.onInspectorWordStartInput,
      onInspectorWordEndInput: view.onInspectorWordEndInput,
      insertGapLabel: view.insertGapLabel,
      onInsertInspectorGap: view.onInsertInspectorGap,
      deleteWordLabel: view.deleteWordLabel,
      onDeleteInspectorWord: view.onDeleteInspectorWord,
      deletePhraseShortcut: view.deletePhraseShortcut,
      onDeletePhrase: view.onDeletePhrase,
      deletePhraseLabel: view.deletePhraseLabel,
      deleteKeyLabel: view.deleteKeyLabel,
      inheritScaleLabel: view.inheritScaleLabel,
      onWordStartInput: view.onWordStartInput,
      onWordEndInput: view.onWordEndInput,
      trackStyle: view.trackStyle,
      trackScaleInputValue: view.trackScaleInputValue,
      trackCurve: view.trackCurve,
      trackCurveOptions: view.trackCurveOptions,
      phraseStyle: view.phraseStyle,
      phrasePositionX: view.phrasePositionX,
      phrasePositionY: view.phrasePositionY,
      phraseScaleInputValue: view.phraseScaleInputValue,
      phraseCurve: view.phraseCurve,
      phraseCurveOptions: view.phraseCurveOptions,
      wordStyle: view.wordStyle,
      wordPositionX: view.wordPositionX,
      wordPositionY: view.wordPositionY,
      wordScaleInputValue: view.wordScaleInputValue,
      wordCurve: view.wordCurve,
      wordCurveOptions: view.wordCurveOptions,
      onTrackStyleChange: view.onTrackStyleChange,
      onTrackColorPreview: view.onTrackColorPreview,
      onTrackScaleInput: view.onTrackScaleInput,
      onTrackScaleBlur: view.onTrackScaleBlur,
      onTrackCurveChange: view.onTrackCurveChange,
      onTrackBezierChange: view.onTrackBezierChange,
      showTrackBezierEditor: view.showTrackBezierEditor,
      onPhraseStyleChange: view.onPhraseStyleChange,
      onPhraseColorPreview: view.onPhraseColorPreview,
      onPhraseScaleInput: view.onPhraseScaleInput,
      onPhraseScaleBlur: view.onPhraseScaleBlur,
      onPhraseCurveChange: view.onPhraseCurveChange,
      onPhraseBezierChange: view.onPhraseBezierChange,
      showPhraseBezierEditor: view.showPhraseBezierEditor,
      onWordStyleChange: view.onWordStyleChange,
      onWordColorPreview: view.onWordColorPreview,
      onWordScaleInput: view.onWordScaleInput,
      onWordScaleBlur: view.onWordScaleBlur,
      onWordCurveChange: view.onWordCurveChange,
      onWordBezierChange: view.onWordBezierChange,
      showWordBezierEditor: view.showWordBezierEditor,
      onPhraseColorInherit: view.onPhraseColorInherit,
      onPhraseStyleInherit: view.onPhraseStyleInherit,
      inheritedPhraseScalePlaceholder: view.inheritedPhraseScalePlaceholder,
      onWordColorInherit: view.onWordColorInherit,
      onWordStyleInherit: view.onWordStyleInherit,
      inheritedWordScalePlaceholder: view.inheritedWordScalePlaceholder,
    }),
    [view.sidebarRenderKey]
  );
  return {
    editorHeaderModel,
    playerControlsModel,
    mixerPanelModel,
    editorTimelineModel,
    editorSidebarModel,
  };
}
